# Generated by Django 4.2.2 on 2023-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_profile_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_num',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Number'),
        ),
    ]
