# Generated by Django 4.2.2 on 2023-06-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_board_profile_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='board',
        ),
    ]
