# Generated by Django 4.2.2 on 2023-06-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
